### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'https://github.com/elahd/esp2ino/releases/latest/download/esp2ino.bin'

### ISSUE THREAD

**Issue by ckmccollim** [elahd/esp2ino#11]
Hello, thank you for your work. I am fairly new at a lot of this firmware flashing stuff. I have Wyze plug WLPP1. I get to the directions where I am to load the esp2ino.bin to the plug and get the following error. The MAC address is correct for my plug, and I got it to list in the command right before this with the list command:
wyze_updater_win.exe list

Any suggestions?

I noticed if I hovered over the esp2ino.bin file on github the address link was different than in the wiki instructions:
https://github.com/elahd/esp2ino/blob/main/release/esp2ino.bin

I also tried this address but got the same error. I have Python 3.9.4 installed on this computer.
Here is a copy and paste from my admin command line.

C:\Users\Chuck\Downloads\esp2ino-main\esp2ino-main\release>wyze_updater_win.exe update -s -d 2CAA8E7BC7E3 -f https://github.com/elahd/esp2ino/releases/latest/download/esp2ino.bin
INFO:root:Trying saved credentials from .tokens.
Traceback (most recent call last):
  File "wyze_updater.py", line 399, in <module>
  File "wyze_updater.py", line 237, in update_devices
OSError: [Errno 22] Invalid argument: 'https://github.com/elahd/esp2ino/releases/latest/download/esp2ino.bin'
[19332] Failed to execute script wyze_updater

**Comment by elahd** [comment]
Hey there!

It looks like I missed updating part of the documentation with the most recent release—sorry about that! It's up to date now. You should be good to go if you replace the `-s` parameter with `-x remote`:

```
wyze_updater_win.exe update -x remote -d 2CAA8E7BC7E3 -f https://github.com/elahd/esp2ino/releases/latest/download/esp2ino.bin
```

If you use the "/blob" URL, WyzeUpdater will try to load the GitHub HTML page at that address instead of the binary file itself. The URL in the documentation is the right one.

Let me know how it goes.

**Comment by elahd** [comment]
Also, see #12. This may hold you up as well. Stay tuned...

**Comment by elahd** [comment]
Alright, try using `https://ota.elahd.com/esp2ino.bin`.

```
wyze_updater_win.exe update -x remote -d 2CAA8E7BC7E3 -f https://ota.elahd.com/esp2ino.bin
```

**Comment by ckmccollim** [comment]
I have finally had a chance to try the new command above and it worked! Success, thank you. I now have a working Tasmota plug. I just finished installing the template, and then finished setting up Tasmota plug-in for OctoPrint, and it all works. Thank you again. Now I'm going to try to update the firmware on a Wyze V2 camera that I have to work with OctoPrint too.

**Comment by elahd** [comment]
Amazing—enjoy!
